### ISSUE TITLE
Упростить patch.txt

### ISSUE THREAD

**Issue by makc-ar** [fjay69/UndertaleTools#1]
Доброго настроения!.. А можно упростить работу с утилитами, чтобы WinPack сам клеил мою текстуру шрифта в оригинальную, которая находится в папке TXTR? К примеру, я создал свой шрифт (.gmx и .png) в GMS сохраняя пропорцию текстуры и положил его в папку FONT_new с тем же названием, которое имеет оригинальный шрифт в папке FONT, но тут, наверное, надо будет ставить префикс имени текстуры. которая находится в папке TXTR для автоматической замены, т.е, к примеру есть текстура в папке TXTR под названием 8.png и текстура шрифта fnt_main_menu.png моего в папке FONT_new. Написать просто в patch.txt следующее:  8_fnt_main_menu.png. А бинарные разметки автоматом же вшиваются?

**Comment by makc-ar** [comment]
А можно добавить поддержку для новых архивов, к примеру https://mega.nz/#!ok4xnLAI!a4lHmMUpglQ6eS3xXqoSgFiLZoZJZ2j2K0zeMbuDJy8

**Comment by fjay69** [comment]
Посмотрю, как будет время.

**Comment by fjay69** [comment]
OK, вроде осилил. Сейчас скачаю игру и проверю.

**Comment by fjay69** [comment]
Да, работает. При распаковке и упаковке добавить параметр **-correctTXTR**.
