### ISSUE TITLE
Undertale data.win file has break. Can pack but don't run.

### ISSUE THREAD

**Issue by haku0011** [fjay69/UndertaleTools#11]
data.win from Steam version.

![image](https://user-images.githubusercontent.com/16457725/46217930-4ffbd580-c37e-11e8-899d-4414201ed6ed.png)

There something wrong...

![image](https://user-images.githubusercontent.com/16457725/46218141-e16b4780-c37e-11e8-9f57-dd6e42593e68.png)

original file lose 1 text at the end of the line.

**Comment by fjay69** [comment]
I didn't tested it properly :( Fixed in 2c0cb1c991621ff161035078d0fa24546834a9cf
