### ISSUE TITLE
Can't Open *.txt Files With GameMakerStringsEditor

### ISSUE THREAD

**Issue by skippergame8** [fjay69/UndertaleTools#12]
I'm trying to make a translation for Fran Bow but I can't open .txt files with GameMakerStringsEditor. It needs a special .strg file. But it doesn't show up when I extract the data.win file. Can you help me?

![adsiz](https://user-images.githubusercontent.com/18694563/46243899-566f6900-c3e1-11e8-9d28-f3ea4e882f15.png)

**Comment by fjay69** [comment]
This feature has been disabled. Just use Notepad to edit translate.txt.

**Comment by skippergame8** [comment]
Okay. Now I have tested it and I believe that I need this feature.

There are line breaks. So I believe that I need to use GameMakerStringsEditor in order to avoid crashes. Can you make this feature optional. Or what do I need to download to be able to use this function.

**Comment by fjay69** [comment]
Here: https://yadi.sk/d/SOsIr8B_zZutjw Argument is -strgWithBr (case sensive)

**Comment by skippergame8** [comment]
This didn't work either. Fortunately using 1.08 version solved the issue. I don't know why or how, but it worked :D . Thank you for your help though.

If anyone else wants to translate Fran Bow please use 1.08 version.
