### ISSUE TITLE
line brake warning

### ISSUE THREAD

**Issue by Scrymmery** [fjay69/UndertaleTools#18]
![image](https://github.com/fjay69/UndertaleTools/assets/49278078/3063effb-d3b8-462e-8173-3d7b0b999c3e)
trying to extract ZoG undertale data.win and this is happening, help with unpacking pls

**Comment by fjay69** [comment]
Привет. Откуда брал программы? С каким аргументами запускал? Я сегодня добавил версию 1.11. Попробуй её только с двумя аргументами: путь к файлу *.win и путь к папке, куда будут складываться распакованные ресурсы.

**Comment by Scrymmery** [comment]
из аргументов был только путь к data.win и директория куда все распаковывается. 11 версия работает, пишет OutOfMemory, но вроде все распаковано корректно, спасибо
