### ISSUE TITLE
Fix this pls...

### ISSUE THREAD

**Issue by JustinGdnz** [fjay69/UndertaleTools#2]
ok... well, i found this tool searching how to extract GameMaker's Files (like dat.win, game.droid, etc) and then reimport it, I used quickbms but... huh... i can only remplace files with the same size or smaller so the problem its that i extracted some file (audiogroup1.dat) with only 2 chunks (FUNC and AUDO) but i cant reimport it... cause it say that the tool didn't found some chuncks but the file only have 2 chuncks... pls fix this

**Comment by fjay69** [comment]
Hello. Attach the example of your file please. I will check it out.

**Comment by JustinGdnz** [comment]
[Audio.zip](https://github.com/fjay69/UndertaleTools/files/1666614/Audio.zip)
there is it... also some mistake, its FORM not FUNC

**Comment by JustinGdnz** [comment]
Thanks but... there's any way to delete the TXTR Chunk? or make that the program didn't print it? because the game didn't detect the audio file and maybe the problem are the TXTR Chunk

**Comment by JustinGdnz** [comment]
I understand that this tool is for undertale but i really want to remplace the audio of a game

**Comment by fjay69** [comment]
I had extracted the file you given to me. I've got many audio files. I packed them. The output file is exact same as original file. What a TXTR chunk you talking about?

**Comment by JustinGdnz** [comment]
![6](https://user-images.githubusercontent.com/35826578/35469600-bf2df768-02fd-11e8-87ff-c3ebbe7e8318.PNG)
![7](https://user-images.githubusercontent.com/35826578/35469603-c6a1bb92-02fd-11e8-9a0e-fe64372c4b42.PNG)
![8](https://user-images.githubusercontent.com/35826578/35469604-c9f15f50-02fd-11e8-83ab-2c56258569f8.PNG)

Umm... idk why it print txtr chunk

**Comment by fjay69** [comment]
OK, I disgreased myself :) Fixed.
