### ISSUE TITLE
Problem when pack

### ISSUE THREAD

**Issue by Tarkoviski** [fjay69/UndertaleTools#3]
Every time that I try to pack the strings back I receive this error:

```
An unhandled exception of type 'System.IndexOutOfRangeException' occurred in WinPack.exe

Additional information: Index was outside the bounds of the array
```

Can you help me, please?

**Comment by fjay69** [comment]
Do you changing fonts or you just changing strings? Then you can send me your translate.txt, I will check it by myself.

**Comment by Tarkoviski** [comment]
Only strings. 

[Here's the strings](https://tarkoviski.github.io/tale.txt)

**Comment by fjay69** [comment]
STRG.txt has 31148 lines. Your translate.txt has 31150 lines.

**Comment by Tarkoviski** [comment]
Thanks for your time, sorry for anything.

**Comment by fjay69** [comment]
It's OK. My program is bad with error notifications. I will try to fix this)
