### ISSUE TITLE
request support of winextract and winpack for psvita.win

### ISSUE THREAD

**Issue by Serhi0** [fjay69/UndertaleTools#4]
i want to translate the game for ps vita and winextract and winpack do not work for the file.win for vita, neither does Adding-custom-glyphs work and I need it for Latin characters. Thank you
P.D (if you need file.win for vita I can pass you link)

**Comment by Darkmet98** [comment]
Check #5

**Comment by fjay69** [comment]
Thank you, Darkmet98.
