### ISSUE TITLE
Error with switch file

### ISSUE THREAD

**Issue by LedyBacer** [fjay69/UndertaleTools#7]
When i try to unpack the undertale switch file i get this error
![image](https://user-images.githubusercontent.com/19615437/45579464-625f1500-b890-11e8-9e13-2d236ad543ff.png)
And something similar with ZoG 2.0 rus file. A lot of warnings and at the end the same thing
![image](https://user-images.githubusercontent.com/19615437/45579521-ea451f00-b890-11e8-9705-d8cde4888e90.png)

**Comment by fjay69** [comment]
Hi. Give me data.win from switch version.

**Comment by LedyBacer** [comment]
> Hi. Give me data.win from switch version.

Here https://yadi.sk/d/7Q4RaAc1xv2BzQ

**Comment by fjay69** [comment]
https://github.com/fjay69/UndertaleTools/releases/tag/switch
